aralhibshi/calo-nutritionist-planner-fe

package-lock.json, package.json, src/App.tsx, src/components/NavBar.tsx, src/index.tsx
=> feat: Add NavBar

.gitignore, package-lock.json, package.json, src/App.tsx, src/components/IngredientTable.tsx, src/components/NavBar.tsx, src/components/SearchToggleButton.tsx, src/config.ts, src/index.tsx, src/pages/Home.tsx, src/pages/Ingredients.tsx
-Adds Table to the Page, with some example data
=> feat: Creates Ingredient Page

package-lock.json, package.json, src/components/ingredient/AddIngredientDialog.tsx, src/components/ingredient/IngredientDetailModal.tsx, src/components/ingredient/IngredientTable.tsx, src/components/search/SearchBar.tsx, src/index.css, src/index.tsx, src/interfaces/ingredient.ts, src/network/ingredient_api.ts
- Implement ingredient search
- Modify ingredient detail modal
- Modify interfaces
=> feat: Ingredient Search

package-lock.json, package.json, src/components/search/SearchBar.tsx, src/pages/ingredient/IngredientTable.tsx
- Implement ingredient search with delay to reduce API calls
=> feat: Ingredient Search with delay to reduce API calls

src/pages/component/ComponentTable.tsx, src/pages/ingredient/IngredientTable.tsx
- Remove setSkip(0) in table components to fix pagination
=> fix: Pagination Skip

src/App.tsx, src/pages/component/ComponentTable.tsx, src/pages/ingredient/IngredientTable.tsx
- Modify searchResult mapping condition to fix empty search result message
=> fix: Empty Search Result Message for Ingredient and Component

src/components/footer/PaginationFooter.tsx, src/pages/meal/MealComponentTable.tsx
- Conditoinally set the pagination count to avoid NaN error
=> fix: Pagination Count Type

src/interfaces/index.ts, src/network/componentApi.ts, src/pages/ingredient/EditIngredientDialog.tsx, src/pages/ingredient/IngredientComponentTable.tsx, src/pages/ingredient/IngredientMealTable.tsx, src/stores/componentStore.ts
- Implement IngredientComponentTable
- Implement IngredientMealTable
- Add zustand states in componentStore
=> feat: Basic Preview of Components with Ingredient

src/network/componentApi.ts, src/network/ingredientApi.ts, src/network/mealApi.ts, src/pages/ingredient/EditIngredientDialog.tsx
- Implement Content-Type Headers for all create & update APIs
=> fix: Content-Type Header for Create/Update APIs

src/interfaces/index.ts, src/network/componentApi.ts, src/network/ingredientApi.ts, src/network/mealApi.ts, src/pages/ingredient/EditIngredientDialog.tsx, src/pages/ingredient/IngredientComponentTable.tsx, src/pages/ingredient/IngredientMealTable.tsx, src/pages/meal/MealTable.tsx, src/stores/mealStore.ts
- Implement condition to fetchMeals with ingredient_id in mealApi
- Implement IngredientMealTable in EditIngredientDialog
- Implement handleTableChange in same dialog/modal
- Modify mealStore to include states for mealTable
=> feat: Meal Table in EditIngredientDialog

src/interfaces/index.ts, src/pages/component/CreateComponentDialog.tsx, src/pages/home/Home.tsx, src/pages/ingredient/CreateIngredientDialog.tsx, src/pages/ingredient/EditIngredientDialog.tsx, src/pages/meal/CreateMealDialog.tsx, src/stores/notificationStore.ts
- Implement snackbar notification in Home component
- Implement notification store to set snackbar open status and message
- Implement setNotify and setMessage in create and update modals/dialogs
=> feat: Snackbar Notifications

src/network/mealApi.ts, src/pages/ingredient/IngredientMealTable.tsx
- Implement material ui primary color from theme onChange of meal values
=> feat: Change Meal Value Color on Ingredient Edit

.gitignore, src/components/footer/PaginationFooter.tsx, src/interfaces/index.ts, src/pages/component/ComponentTable.tsx, src/pages/ingredient/EditIngredientDialog.tsx, src/pages/ingredient/IngredientComponentTable.tsx, src/pages/ingredient/IngredientMealTable.tsx, src/pages/ingredient/IngredientTable.tsx, src/pages/meal/MealTable.tsx, src/stores/entityStore.ts
- Implement dynamic fetch/take amount based on viewport size in tables
- Implement update pagination page amount based on fetch/take amount
- Implement take, setTake, & setTakeCondition in entity store
=> feat: Dynamic Fetch (Take) Entity Amount

src/components/footer/PaginationFooter.tsx, src/components/search/SearchTypeDropdown.tsx, src/interfaces/index.ts, src/stores/entityStore.ts
- Implement currentPage and setCurrentPage in entityStore
- setCurrentPage on entity type change in searchTypeDropDown
- Implement currentPage in PaginationFooter
=> fix: Current Page Number

src/components/footer/PaginationFooter.tsx, src/components/search/SearchBar.tsx, src/interfaces/index.ts, src/stores/entityStore.ts
- Implement separate skip and current page for search results
=> fix: Search Entity Pagination

src/components/footer/PaginationFooter.tsx, src/components/search/SearchBar.tsx, src/interfaces/index.ts, src/pages/component/ComponentTable.tsx, src/pages/ingredient/IngredientComponentTable.tsx, src/pages/ingredient/IngredientMealTable.tsx, src/pages/ingredient/IngredientTable.tsx, src/pages/meal/MealComponentTable.tsx, src/pages/meal/MealTable.tsx, src/stores/entityStore.ts, src/stores/searchStore.ts
- Separate Pagination page values based on separate zustand stores
- Move table result zustand states from searchStore to entityStore
=> fix: Pagination & Table Results

package-lock.json, package.json, src/interfaces/index.ts, src/network/exportApi.ts, src/pages/home/Home.tsx, src/stores/searchStore.ts, src/stores/userStore.ts, src/utils/stringUtils.ts
- Implement Export Api and Export Button for all Entities
- Components Export will not work
- Implement stringUtils file
=> feat: Export Meals, Ingredients, & Components

src/App.tsx, src/interfaces/index.ts, src/network/exportApi.ts, src/pages/home/Home.tsx, src/stores/userStore.ts
- Send exported data to verified email
=> feat: Export Data

src/pages/component/ComponentTable.tsx, src/pages/ingredient/IngredientTable.tsx, src/pages/meal/MealTable.tsx, src/theme/theme.ts
- Implement tooltips for all action buttons on entity tables
=> feat: Tooltip for Table Aciton Buttons

src/pages/ingredient/DialogComponentTable.tsx, src/pages/ingredient/DialogMealTable.tsx
- Switch from vertical to horizontal arrow to indicate value changes
=> fix: Dialog Entity Table Row Height

src/pages/home/Home.tsx, src/pages/ingredient/DialogComponentTable.tsx, src/pages/ingredient/DialogMealTable.tsx, src/pages/ingredient/IngredientPlaygroundDialog.tsx
- Fix playground grid/grid efficieny and code indentation
- Modify grid ratio to give more space to right-hand side of playground
- Change ingredients, components, and meals icons
=> fix: Playground and Homepage Styling

src/index.css, src/pages/ingredient/IngredientTable.tsx, src/pages/meal/MealTable.tsx
- Modify styling for all main entity tables
- Slightly restructure meal table
=> fix: Main Entity Table Styling

src/validation/ingredientFormValidation.ts
- Allow 0 values for create ingredient macros
=> fix: Ingredient Yup Validation Schema

src/pages/meal/MealComponentTable.tsx
- Correct create meal dialog macros calculation
=> fix: Meal Create Calculation

src/pages/ingredient/DialogComponentTable.tsx, src/pages/ingredient/DialogMealTable.tsx, src/pages/meal/MealTable.tsx
- Include total meal grams in meal table
- Remove unit from dialog meal and dialog component tables
=> feat: Total Meal Grams & Remove Unit

src/pages/component/CreateComponentDialog.tsx, src/pages/component/EditComponentDialog.tsx, src/pages/ingredient/CreateIngredientDialog.tsx, src/pages/ingredient/EditIngredientDialog.tsx, src/validation/componentFormValidation.ts, src/validation/ingredientFormValidation.ts
- Implement valid category select in create/edit ingredient/component
=> feat: Category Select in Create/Edit Ingred/Compo

src/pages/ingredient/DialogMealTable.tsx
- Correct playground dialog meal table calculation
=> fix: Playground Meal Table Calculation
